/**
 * Config Guard — pi. Blocks the model's write/edit and bash tools from mutating
 * the derived agent dir. ~/.claude is the source of truth; the agent dir is
 * regenerated by settings-sync (or, for glm-pi, the launcher) — never hand-edited.
 *
 * agent dir via getAgentDir(): honors PI_CODING_AGENT_DIR, else ~/.pi/agent. A
 * hardcoded path would miss glm-pi's /tmp/glm-pi-$USER.
 *
 * bash guard is substring + write-signal, not a shell parser:
 *  - ponytail: a read bundled with a write-word/redirect into the dir is blocked
 *    and the model retries split. Fails safe. Add a target-resolving tokenizer
 *    if read-with-redirect false positives bite.
 *  - ponytail: first-word dispatch misses find -exec / xargs / $() / >(sub).
 *    Add if the model uses those to mutate the dir.
 * Reads (cat/ls/grep/diff/wc/sed-without-i) stay allowed.
 *
 * Only intercepts the MODEL's tool_call. pi's own writes (auth.json,
 * lastChangelogVersion, sessions) don't fire tool_call, so blocking the whole
 * dir can't break them.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { getAgentDir } from "@earendil-works/pi-coding-agent";
import path from "node:path";
import os from "node:os";

const WRITE_OPS = /\b(tee|sed|dd|cp|install|rsync|mv|rm|rmdir|shred|unlink)\b/;
const SED_INPLACE = /(^|\s)-i\w*\b|--in-place\b/;
// redirect op at a token boundary (start/space), not fd-to-fd (2>&1). Applied after
// stripping string literals and [[ ]]/(( )) so prose ">" and test ">" don't trip.
const REDIR = /(?:^|\s)(?:&>>?|>>?>|\d*>)(?!&\d)|>>?(?=\|)/;

// Strip quoted strings and [[ ]]/(( )) contexts so a ">" inside prose ("->",
// "=>", "$a > $b") doesn't look like a redirect. ponytail: naive — escaped
// quotes / nested [[ ]] aren't handled; add a real lexer if false-positives bite.
function stripContexts(c: string): string {
  return c
    .replace(/"([^"\\]|\\.)*"/g, " ")
    .replace(/'[^']*'/g, " ")
    .replace(/\[\[[\s\S]*?\]\]/g, " ")
    .replace(/\(\([\s\S]*?\)\)/g, " ");
}

function bashWritesTo(command: string, dir: string, home: string): boolean {
  const c = stripContexts(command).replace(/~/g, home).replace(/\$HOME\b/g, home);
  // dir present as a path token (followed by sep or end) — avoids $dir-foo hits
  const dirRe = new RegExp(dir.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "(?:[/\\\\]|$)");
  if (!dirRe.test(c)) return false;
  for (const seg of c.split(/&&|\|\||;|(?<!>)\|(?![&|])/)) {
    if (REDIR.test(seg)) return true;
    const w = seg.trim().replace(/^sudo\s+/, "").replace(/^(?:\w+=\S+\s+)+/, "").match(/^(\w[\w-]*)/);
    if (w && WRITE_OPS.test(w[1])) {
      if (w[1] === "sed" && !SED_INPLACE.test(seg)) continue; // sed without -i reads
      return true;
    }
  }
  return false;
}

export default function (pi: ExtensionAPI) {
  const dir = getAgentDir();
  const prefix = dir + path.sep;
  const home = os.homedir();

  const reason = (via: string, target: string, extra = "") =>
    `BLOCKED: ${target} is a derived target under the pi agent dir (${dir}), reached via ${via}${extra}. ` +
    `Edit the ~/.claude/ source (or the launcher), then re-sync / re-launch. See ~/.claude/pi/README.md.`;

  pi.on("tool_call", async (event, ctx) => {
    if (event.toolName === "write" || event.toolName === "edit") {
      const raw = (event.input as { path?: string } | undefined)?.path;
      if (raw) {
        const r = path.resolve(raw.replace(/^~/, home));
        if (r === dir || r.startsWith(prefix)) {
          if (ctx.hasUI) ctx.ui.notify(`Blocked ${event.toolName} to derived path: ${r}`, "warning");
          return { block: true, reason: reason(event.toolName, r) };
        }
      }
    } else if (event.toolName === "bash") {
      const command = (event.input as { command?: string } | undefined)?.command;
      if (command && bashWritesTo(command, dir, home)) {
        if (ctx.hasUI) ctx.ui.notify(`Blocked bash write to derived path: ${dir}`, "warning");
        const snip = command.length > 100 ? command.slice(0, 97) + "..." : command;
        return { block: true, reason: reason("bash", dir, ` (command: ${snip})`) };
      }
    }
    return undefined;
  });
}
