/**
 * Config Guard — pi. Blocks the model's write/edit and bash tools from mutating
 * the derived agent dir. ~/.claude is the source of truth; the agent dir is
 * regenerated by settings-sync (or, for glm-pi, the launcher) — never hand-edited.
 *
 * Watched dirs (all derived from ~/.claude — never hand-edit any of them):
 *   - getAgentDir(): the LIVE dir pi runs against (honors PI_CODING_AGENT_DIR,
 *     else ~/.pi/agent). Under glm-pi this is /tmp/glm-pi-$USER.
 *   - ~/.pi/agent: the default dir that settings-sync populates and the glm-pi
 *     launcher reads from. getAgentDir() does NOT cover this when the live dir is
 *     elsewhere, so a model write to ~/.pi/agent used to sail through; watch it
 *     explicitly. Deduped when both resolve to the same path (plain pi).
 *
 * bash guard is substring + write-signal, not a shell parser:
 *  - redirects are target-aware: a read of the dir with stderr to /dev/null (or
 *    any redirect whose resolved target isn't the dir) is allowed; only a redirect
 *    whose target is the dir blocks. Relative targets resolve against cwd.
 *  - ponytail: first-word dispatch misses find -exec / xargs / $() / >(sub).
 *    Add if the model uses those to mutate the dir.
 * Reads (cat/ls/grep/diff/wc/sed-without-i) stay allowed.
 *
 * Only intercepts the MODEL's tool_call. pi's own writes (auth.json,
 * lastChangelogVersion, sessions) don't fire tool_call, so blocking the whole
 * dir can't break them.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { getAgentDir } from "@earendil-works/pi-coding-agent";
import path from "node:path";
import os from "node:os";

const WRITE_OPS = /\b(tee|sed|dd|cp|install|rsync|mv|rm|rmdir|shred|unlink)\b/;
const SED_INPLACE = /(^|\s)-i\w*\b|--in-place\b/;
// write-redirect operator capturing its target file token (excludes fd-to-fd like
// 2>&1 and input redirects <). Applied after stripContexts + ~/$HOME expand, so
// prose ">" is already gone. ponytail: target-aware - a read of the dir with stderr
// to /dev/null (or any redirect whose target isn't the dir) is allowed; only a
// redirect whose resolved target is the dir blocks. Relative targets resolve
// against process.cwd(); protected dirs are absolute, so a bareword target only
// hits when cwd is in the dir (rare) - strictly weaker than the old any-redirect rule.
const WRITE_REDIR = /(?:^|\s)(?:&>>?|\d*>>?\|?)(?!&\d)\s*(\S+)/g;

// Strip quoted strings and [[ ]]/(( )) contexts so a ">" inside prose ("->",
// "=>", "$a > $b") doesn't look like a redirect. ponytail: naive — escaped
// quotes / nested [[ ]] aren't handled; add a real lexer if false-positives bite.
function stripContexts(c: string): string {
  return c
    .replace(/"([^"\\]|\\.)*"/g, " ")
    .replace(/'[^']*'/g, " ")
    .replace(/\[\[[\s\S]*?\]\]/g, " ")
    .replace(/\(\([\s\S]*?\)\)/g, " ");
}

function bashWritesTo(command: string, dir: string, home: string): boolean {
  const c = stripContexts(command).replace(/~/g, home).replace(/\$HOME\b/g, home);
  // dir present as a path token (followed by sep or end) — avoids $dir-foo hits
  const dirRe = new RegExp(dir.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "(?:[/\\\\]|$)");
  if (!dirRe.test(c)) return false;
  for (const seg of c.split(/&&|\|\||;|(?<!>)\|(?![&|])/)) {
    // a redirect only counts if its resolved target is the dir (not /dev/null etc.)
    WRITE_REDIR.lastIndex = 0;
    let m = WRITE_REDIR.exec(seg);
    while (m !== null) {
      const target = path.resolve(m[1]);
      if (target === dir || target.startsWith(dir + path.sep)) return true;
      m = WRITE_REDIR.exec(seg);
    }
    const w = seg.trim().replace(/^sudo\s+/, "").replace(/^(?:\w+=\S+\s+)+/, "").match(/^(\w[\w-]*)/);
    if (w && WRITE_OPS.test(w[1])) {
      if (w[1] === "sed" && !SED_INPLACE.test(seg)) continue; // sed without -i reads
      return true;
    }
  }
  return false;
}

export default function (pi: ExtensionAPI) {
  const home = os.homedir();
  const liveDir = getAgentDir();
  const defaultDir = path.join(home, ".pi", "agent");
  // Dedupe (plain pi: both resolve to ~/.pi/agent).
  const protectedDirs = Array.from(new Set([liveDir, defaultDir].map((d) => path.resolve(d))));

  const underDir = (r: string): string | undefined =>
    protectedDirs.find((d) => r === d || r.startsWith(d + path.sep));

  const reason = (via: string, target: string, dir: string, extra = "") =>
    `BLOCKED: ${target} is a derived target under the pi agent dir (${dir}), reached via ${via}${extra}. ` +
    `Edit the ~/.claude/ source (or the launcher), then re-sync / re-launch. See ~/.claude/pi/README.md.`;

  pi.on("tool_call", async (event, ctx) => {
    if (event.toolName === "write" || event.toolName === "edit") {
      const raw = (event.input as { path?: string } | undefined)?.path;
      if (raw) {
        const r = path.resolve(raw.replace(/^~/, home));
        const dir = underDir(r);
        if (dir) {
          if (ctx.hasUI) ctx.ui.notify(`Blocked ${event.toolName} to derived path: ${r}`, "warning");
          return { block: true, reason: reason(event.toolName, r, dir) };
        }
      }
    } else if (event.toolName === "bash") {
      const command = (event.input as { command?: string } | undefined)?.command;
      if (command) {
        const dir = protectedDirs.find((d) => bashWritesTo(command, d, home));
        if (dir) {
          if (ctx.hasUI) ctx.ui.notify(`Blocked bash write to derived path: ${dir}`, "warning");
          const snip = command.length > 100 ? command.slice(0, 97) + "..." : command;
          return { block: true, reason: reason("bash", dir, dir, ` (command: ${snip})`) };
        }
      }
    }
    return undefined;
  });
}
