/**
 * Config Guard — pi port of the opencode config-guard hook.
 *
 * `~/.claude` is the single source of truth; `~/.pi/agent` is the derived
 * target regenerated by `sync pi`. This extension blocks the model's
 * write/edit tools from hand-editing anything under the derived agent dir, so
 * drift can't sneak in. Edit the source in `~/.claude`, then re-sync.
 *
 * Loaded directly from source by pi via the `extensions` pointer in
 * ~/.pi/agent/settings.json (itself a wholesale copy of ~/.claude/pi/settings.json).
 * The extension itself is never synced — pi reads it from source.
 *
 * Parity notes vs the opencode hook (~/.claude/opencode/plugins/config-guard.js):
 *  - opencode blocks edit/write/apply_patch under ~/.config/opencode/
 *  - here we block write/edit under ~/.pi/agent/ (pi has no apply_patch built-in)
 *  - same known gap: bash redirection (echo > file) is not guarded, by design
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import path from "node:path";
import os from "node:os";

export default function (pi: ExtensionAPI) {
  // Everything under here is machine-local derived state, not source of truth.
  // settings-sync manages settings.json + CLAUDE.md; auth.json/sessions/bin/ are
  // pi-internal. None of it should be hand-edited by the model. If you ever need
  // the model to author something under ~/.pi/agent/, narrow DERIVED_FILES.
  const DERIVED_DIR = path.join(os.homedir(), ".pi", "agent");
  const prefix = DERIVED_DIR + path.sep;

  // The two files settings-sync actually regenerates for pi. Kept for reference /
  // optional narrow mode; the default guard blocks the whole derived dir.
  const DERIVED_FILES = new Set([
    path.join(DERIVED_DIR, "settings.json"),
    path.join(DERIVED_DIR, "CLAUDE.md"),
  ]);

  // Tools that mutate files on disk. Add custom write-like tool names here if
  // you register any extension tools that write to disk.
  const blockingTools = new Set(["write", "edit"]);

  pi.on("tool_call", async (event, ctx) => {
    if (!blockingTools.has(event.toolName)) return undefined;

    const raw = (event.input as { path?: string } | undefined)?.path;
    if (!raw) return undefined;

    // pi's built-in tools resolve paths and strip a leading @, but expand ~
    // ourselves so a tilde/relative path can't slip past the prefix check.
    const resolved = path.resolve(raw.replace(/^~/, os.homedir()));

    const isDerived = resolved === DERIVED_DIR || resolved.startsWith(prefix);
    if (!isDerived) return undefined;
    void DERIVED_FILES; // available if you switch to file-level blocking

    const reason =
      `BLOCKED: ${resolved} is a derived target synced from ~/.claude/. ` +
      `Edit the ~/.claude/ source instead, then run ` +
      `\`sync pi\` (add \`--force\` if CLAUDE.md has diverged). ` +
      `See ~/.claude/pi/README.md.`;

    if (ctx.hasUI) {
      ctx.ui.notify(`Blocked ${event.toolName} to derived path: ${resolved}`, "warning");
    }
    return { block: true, reason };
  });
}
