// Config Guard — opencode plugin (mirrors ~/.claude/pi/extensions/config-guard.ts).
//
// `~/.claude` is the single source of truth; the opencode config dir is the
// derived target, regenerated by `settings-sync opencode`. This plugin blocks
// the model from hand-editing anything under the config dir, so drift can't
// sneak in. Edit the source in `~/.claude`, then re-sync.
//
// The config dir is resolved the way opencode/superpowers do: honor
// $OPENCODE_CONFIG_DIR, falling back to ~/.config/opencode. A hardcoded
// ~/.config/opencode would miss an override (same bug class as pi's
// PI_CODING_AGENT_DIR, which the pi-side guard already handles).
//
// Coverage:
//  - edit/write/apply_patch tool calls targeting a path under the config dir -> blocked
//  - bash tool calls that write to / mutate a path under the config dir -> blocked
//    (redirection, tee, sed -i, dd of=, cp/install/rsync dest,
//     mv/rm/rmdir/shred/unlink operands). Closes the echo>file loophole.
//
// Not a shell parser — a conservative heuristic. Reads of the config dir via
// bash (cat, ls, grep, diff, wc, stat) carry no write operator and aren't
// dispatched as mutating commands, so they remain allowed.
//
// Tool input shapes (confirmed from real opencode session records):
//   bash  -> { command }
//   write -> { filePath, content }
//   edit  -> { filePath, oldString, newString }
// The hook reads args from output.args (the pattern this plugin already used),
// with input.args as a fallback in case the runtime passes them there.
import path from "path"
import os from "os"

const home = os.homedir()
// Respect opencode's config dir override; fall back to ~/.config/opencode.
const CONFIG_DIR = (process.env.OPENCODE_CONFIG_DIR && process.env.OPENCODE_CONFIG_DIR.trim())
  ? path.resolve(process.env.OPENCODE_CONFIG_DIR.replace(/^~/, home))
  : path.join(home, ".config", "opencode")

function expandHome(p) {
  return p
    .replace(/^~/, home)
    .replace(/\$HOME/g, home)
    .replace(/\$\{HOME\}/g, home)
}

// Strip one layer of surrounding quotes. Compare by char code to avoid fragile
// nested quote literals (a hand-written quote-in-quotes pair is error-prone
// and was the source of an unterminated-string bug in the pi twin).
function stripQuotes(s) {
  if (s.length >= 2) {
    const a = s.charCodeAt(0)
    const b = s.charCodeAt(s.length - 1)
    // 34 = double quote, 39 = single quote
    if ((a === 34 && b === 34) || (a === 39 && b === 39)) return s.slice(1, -1)
  }
  return s
}

// First command word of a segment, skipping a leading `sudo` and any
// `FOO=bar` env assignments, so `sudo rm x` / `FOO=1 tee x` dispatch correctly.
function firstCommandWord(seg) {
  const s = seg.trim().replace(/^sudo\s+/, "").replace(/^(?:[A-Za-z_]\w*=\S+\s+)+/, "")
  const m = s.match(/^([A-Za-z_][\w-]*)/)
  return m ? m[1] : ""
}

// Returns the first path the command writes to / mutates under `dir`, else null.
function bashWriteTarget(command, dir) {
  const sep = path.sep
  const resolve = (p) => path.resolve(expandHome(stripQuotes(p)))
  const under = (p) => {
    const r = resolve(p)
    return r === dir || r.startsWith(dir + sep)
  }
  const targetOf = (p) => (under(p) ? resolve(p) : null)

  // file-targeting redirection: append/overwrite, fd-prefixed, both-streams, noclobber
  const redir = /(?:[12]>>?|&>>|&>|>>|>\||>)/g

  // Split on sequencing operators, but NOT on the | in >| or |& — those are part
  // of a redirect/pipe operator, not a statement separator.
  for (const seg of command.split(/&&|\|\||;|(?<!>)\|(?![&|])/)) {
    // 1) redirection to a file (works for any command, incl. heredoc cat>f <<E)
    redir.lastIndex = 0
    let m
    while ((m = redir.exec(seg)) !== null) {
      const rest = seg.slice(m.index + m[0].length)
      const tok = rest.match(/^\s*(\S+)/)
      if (tok) {
        const t = targetOf(tok[1])
        if (t) return t
      }
    }

    const cmd = firstCommandWord(seg)
    const toks = seg.trim().split(/\s+/).slice(1).filter((t) => t && !t.startsWith("-"))

    // 2) tee writes to its path operands
    if (cmd === "tee") {
      for (const t of toks) {
        const r = targetOf(t)
        if (r) return r
      }
    }

    // 3) sed in-place edits its file operands (without -i it only reads)
    if (cmd === "sed" && /(^|\s)-i\b|(^|\s)--in-place\b/.test(seg)) {
      for (const t of toks) {
        const r = targetOf(t)
        if (r) return r
      }
    }

    // 4) dd of=PATH
    if (cmd === "dd") {
      const dd = /\bof=(\S+)/g
      while ((m = dd.exec(seg)) !== null) {
        const r = targetOf(m[1])
        if (r) return r
      }
    }

    // 5) cp/install/rsync: only the destination (last operand) is mutated
    if (cmd === "cp" || cmd === "install" || cmd === "rsync") {
      if (toks.length) {
        const r = targetOf(toks[toks.length - 1])
        if (r) return r
      }
    }

    // 6) mv: any operand is mutated (covers move-out and move-in)
    //    rm/rmdir/shred/unlink: any operand is deleted
    if (cmd === "mv" || cmd === "rm" || cmd === "rmdir" || cmd === "shred" || cmd === "unlink") {
      for (const t of toks) {
        const r = targetOf(t)
        if (r) return r
      }
    }
  }
  return null
}

export const ConfigGuard = async () => {
  return {
    "tool.execute.before": async (input, output) => {
      const tool = input && input.tool
      const args = (output && output.args) || (input && input.args) || {}

      // 1) edit/write/apply_patch -> filePath arg
      if (tool === "edit" || tool === "write" || tool === "apply_patch") {
        const filePath = args.filePath || args.path || ""
        if (filePath) {
          const resolved = path.resolve(filePath)
          if (resolved === CONFIG_DIR || resolved.startsWith(CONFIG_DIR + path.sep)) {
            throw new Error(
              `BLOCKED: ${resolved} is a derived target under the opencode config dir ` +
              `(${CONFIG_DIR}), reached via ${tool}. It's synced from ~/.claude/ via ` +
              `settings-sync (or regenerated from $OPENCODE_CONFIG_DIR). Edit the ` +
              `~/.claude/ source, then run \`settings-sync opencode\` (add \`--force\` ` +
              `if a derived file has diverged). See AGENTS.md config management rules.`,
            )
          }
        }
      }

      // 2) bash -> scan for a write/mutate target under the config dir
      if (tool === "bash") {
        const command = args.command || args.cmd || ""
        if (command) {
          const target = bashWriteTarget(command, CONFIG_DIR)
          if (target) {
            const snippet = command.length > 120 ? command.slice(0, 117) + "..." : command
            throw new Error(
              `BLOCKED: ${target} is a derived target under the opencode config dir ` +
              `(${CONFIG_DIR}), reached via bash (command: ${snippet}). Edit the ` +
              `~/.claude/ source, then run \`settings-sync opencode\`. ` +
              `See AGENTS.md config management rules.`,
            )
          }
        }
      }
    },
  }
}
