// Config Guard — opencode (mirrors ~/.claude/pi/extensions/config-guard.ts).
// Blocks the model's write/edit/apply_patch and bash tools from mutating the
// derived config dir. ~/.claude is the source of truth; the config dir is
// regenerated by settings-sync — never hand-edited.
//
// config dir honors $OPENCODE_CONFIG_DIR, else ~/.config/opencode (same env-
// override pattern the superpowers plugin uses; a hardcoded path would miss it).
//
// bash guard is substring + write-signal, not a shell parser:
//  - redirects are target-aware: a read of the dir with stderr to /dev/null (or
//    any redirect whose resolved target isn't the dir) is allowed; only a redirect
//    whose target is the dir blocks. Relative targets resolve against cwd.
//  - ponytail: first-word dispatch misses find -exec / xargs / $() / >(sub).
//    Add if the model uses those to mutate the dir.
// Reads (cat/ls/grep/diff/wc/sed-without-i) stay allowed.
//
// Tool input shapes (from real opencode session records):
//   bash -> { command }   |   write/edit -> { filePath, ... }   (hook reads output.args)
import path from "path"
import os from "os"

const home = os.homedir()
const CONFIG_DIR = (process.env.OPENCODE_CONFIG_DIR && process.env.OPENCODE_CONFIG_DIR.trim())
  ? path.resolve(process.env.OPENCODE_CONFIG_DIR.replace(/^~/, home))
  : path.join(home, ".config", "opencode")

const WRITE_OPS = /\b(tee|sed|dd|cp|install|rsync|mv|rm|rmdir|shred|unlink)\b/
const SED_INPLACE = /(^|\s)-i\w*\b|--in-place\b/
// write-redirect operator capturing its target file token (excludes fd-to-fd like
// 2>&1 and input redirects <). Applied after stripContexts + ~/$HOME expand, so
// prose ">" is already gone. ponytail: target-aware - a read of the dir with stderr
// to /dev/null (or any redirect whose target isn't the dir) is allowed; only a
// redirect whose resolved target is the dir blocks. Relative targets resolve
// against process.cwd(); protected dirs are absolute, so a bareword target only
// hits when cwd is in the dir (rare) - strictly weaker than the old any-redirect rule.
const WRITE_REDIR = /(?:^|\s)(?:&>>?|\d*>>?\|?)(?!&\d)\s*(\S+)/g

// Strip quoted strings and [[ ]]/(( )) so prose ">" ("->", "=>", "$a > $b")
// doesn't look like a redirect. ponytail: naive — add a lexer if it bites.
function stripContexts(c) {
  return c
    .replace(/"([^"\\]|\\.)*"/g, " ")
    .replace(/'[^']*'/g, " ")
    .replace(/\[\[[\s\S]*?\]\]/g, " ")
    .replace(/\(\([\s\S]*?\)\)/g, " ")
}

function bashWritesTo(command, dir) {
  const c = stripContexts(command).replace(/~/g, home).replace(/\$HOME\b/g, home)
  const dirRe = new RegExp(dir.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "(?:[/\\\\]|$)")
  if (!dirRe.test(c)) return false
  for (const seg of c.split(/&&|\|\||;|(?<!>)\|(?![&|])/)) {
    // a redirect only counts if its resolved target is the dir (not /dev/null etc.)
    WRITE_REDIR.lastIndex = 0
    let m = WRITE_REDIR.exec(seg)
    while (m !== null) {
      const target = path.resolve(m[1])
      if (target === dir || target.startsWith(dir + path.sep)) return true
      m = WRITE_REDIR.exec(seg)
    }
    const w = seg.trim().replace(/^sudo\s+/, "").replace(/^(?:\w+=\S+\s+)+/, "").match(/^(\w[\w-]*)/)
    if (w && WRITE_OPS.test(w[1])) {
      if (w[1] === "sed" && !SED_INPLACE.test(seg)) continue
      return true
    }
  }
  return false
}

export const ConfigGuard = async () => {
  return {
    "tool.execute.before": async (input, output) => {
      const tool = input && input.tool
      const args = (output && output.args) || (input && input.args) || {}
      const block = (via, target, extra = "") => {
        throw new Error(
          `BLOCKED: ${target} is a derived target under the opencode config dir (${CONFIG_DIR}), ` +
          `reached via ${via}${extra}. Edit the ~/.claude/ source, then run ` +
          `\`settings-sync opencode\` (add \`--force\` if a derived file diverged). ` +
          `See AGENTS.md config management rules.`,
        )
      }
      if (tool === "edit" || tool === "write" || tool === "apply_patch") {
        const filePath = args.filePath || args.path || ""
        if (filePath) {
          const r = path.resolve(filePath)
          if (r === CONFIG_DIR || r.startsWith(CONFIG_DIR + path.sep)) block(tool, r)
        }
      } else if (tool === "bash") {
        const command = args.command || args.cmd || ""
        if (command && bashWritesTo(command, CONFIG_DIR)) {
          block("bash", CONFIG_DIR, ` (command: ${command.length > 100 ? command.slice(0, 97) + "..." : command})`)
        }
      }
    },
  }
}
